# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    access_key = "e2eaccesskey"
    bucket     = "e2e-state"
    endpoints = {
      s3 = "http://127.0.0.1:19000"
    }
    key                         = "dns/terraform.tfstate"
    region                      = "us-east-1"
    secret_key                  = "e2esecretkey"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    use_lockfile                = true
    use_path_style              = true
  }
}
