"""The attribution ban, exercised on both sides.

A gate never seen to reject is not known to work — and a gate that rejects
everything is equally broken, which only testing the rejections would not
notice. These cases were behavioural assertions inside check-hooks.sh, where
they ran once per gate invocation and could not be extended without writing
more shell.
"""

from __future__ import annotations

import pytest
from scripts.checks.no_ai_attribution import main, offences, prose

REJECTED = [
    pytest.param(
        "feat(x): a change\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
        id="trailer",
    ),
    pytest.param("feat(x): a change\n\nGenerated with Claude Code.\n", id="generated"),
    pytest.param("feat(x): a change\n\nThis was generated by an AI.\n", id="by-an-ai"),
    pytest.param("feat(x): a change\n\nWritten by ChatGPT.\n", id="written-by"),
    pytest.param("feat(x): a change\n\nAssisted by Copilot.\n", id="assisted-by"),
    pytest.param("feat(x): a change\n\nDrafted with GPT-5.\n", id="model-name"),
    pytest.param("feat(x): a change\n\nCourtesy of OpenAI.\n", id="vendor"),
    pytest.param("feat(x): a change\n\nclaude wrote this bit.\n", id="bare-name"),
    pytest.param("feat(x): a change\n\nAsked Claude, then fixed it.\n", id="mid-line"),
]

ACCEPTED = [
    pytest.param(
        "feat(x): a change\n\nAn ordinary body naming the reason.\n", id="ordinary"
    ),
    pytest.param(
        "feat(x): a change\n\nAdds .claude/hooks/guard-main-branch.py.\n",
        id="tool-path",
    ),
    pytest.param(
        "docs(agents): describe .claude/skills/powerdns-facts/SKILL.md\n",
        id="tool-path-in-subject",
    ),
    pytest.param(
        "fix(ci): the runner clears $HOME/.claude/settings.json\n",
        id="tool-path-with-prefix",
    ),
    pytest.param("feat(x): raise the AI-free bar\n", id="the-letters-alone"),
]


@pytest.mark.parametrize("message", REJECTED)
def test_a_claim_of_authorship_is_rejected(message):
    """Every shape the claim takes must be refused."""
    assert offences(message), f"accepted a claim: {message!r}"


@pytest.mark.parametrize("message", ACCEPTED)
def test_an_ordinary_message_is_accepted(message):
    """A gate that rejects everything is as broken as one that rejects nothing."""
    assert offences(message) == [], f"rejected an ordinary message: {message!r}"


def test_the_reported_line_is_the_offending_one():
    """The line number is what makes the failure actionable rather than a verdict."""
    message = "feat(x): a change\n\nbody\n\nCo-Authored-By: Claude <x@y>\n"
    assert [number for number, _ in offences(message)] == [5]


def test_only_paths_under_the_tool_directory_are_stripped():
    """Widening the strip is the tempting fix when this fires.

    It is also how the rule gets disabled: every path stripped is a line the
    classifier never sees.
    """
    assert prose("see .claude/hooks/x.py here") == "see  here"
    assert prose("claude/hooks/x.py") == "claude/hooks/x.py"


def test_a_missing_argument_is_a_usage_error(capsys):
    """pre-commit passes the path; a hook wired wrong must say so, not pass."""
    assert main([]) == 2
    assert "usage:" in capsys.readouterr().err


def test_the_file_is_read_and_the_status_reflects_it(tmp_path, capsys):
    """The exit status is the whole interface git sees."""
    good = tmp_path / "good"
    good.write_text("feat(x): a change\n")
    assert main([str(good)]) == 0

    bad = tmp_path / "bad"
    bad.write_text("feat(x): a change\n\nCo-Authored-By: Claude <x@y>\n")
    assert main([str(bad)]) == 1
    assert "golden rule 6" in capsys.readouterr().err
